# Docker Compose for Shorts Analyzer with Co-op Integration

services:
  # Main application with host networking to access co-op service
  app:
    build: .
    network_mode: "host"  # This allows access to localhost:8080 co-op service
    environment:
      - NODE_ENV=production
      - PORT=4001  # Set specific port since we're using host network
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
      - ADMIN_API_KEY=${ADMIN_API_KEY}
      - ADMIN_SECRET=${ADMIN_SECRET}
      # Database connection using host network
      - DATABASE_URL=postgresql://${DB_USER:-shorts_user}:${DB_PASSWORD:-shorts_password}@localhost:5433/${DB_NAME:-shorts_analyzer}
      # Redis connection using host network
      - REDIS_URL=redis://localhost:6380
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    depends_on:
      - postgres
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=${DB_NAME:-shorts_analyzer}
      - POSTGRES_USER=${DB_USER:-shorts_user}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-shorts_password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"  # External port 5433
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-shorts_user}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis for caching and queues
  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"  # External port 6380
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

# No custom networks needed with host networking
